### ISSUE TITLE
Bedienungshilfen > Smart Assistant

### ISSUE THREAD

**Issue by MeiGuddet** [berlinux2016/MIUI9-ger#115]
- **MIUI Version:** 7.11.9
- **Device name:** Redmi 3/ido

**Screenshot/Description:** Im genannten Menü sind jede Menge chinesische Zeichen, s. Screenshot:
![screenshot_2017-11-11-13-15-51-732_com android settings](https://user-images.githubusercontent.com/22425869/32690468-84744d3a-c6f7-11e7-9a67-d38fe9c7f2fc.png)

**Comment by MeiGuddet** [comment]
Weiß nicht, in welcher apk der sich versteckt, sonst hätte ich ja mal eine Übersetzungsversuch gestartet ;-)

**Comment by Henry2o1o** [comment]
da sist noch einiges offen, habe es mit "##" markiert

Zeile 1236  `<string name="quickstart_accessibility_description">##该服务为 [ 桌面信息助手 - 快捷功能卡片 ] 提供部分第三方应用页面的跳转支持，关闭该服务会导致页面跳转失效。</string>`

https://github.com/berlinux2016/MIUI9-ger/blob/master/German/main/PersonalAssistant.apk/res/values-de/strings.xml

**Comment by Henry2o1o** [comment]
Z 1236
https://github.com/berlinux2016/MIUI9-ger/blob/master/German/main/PersonalAssistant.apk/res/values-de/strings.xml

**Comment by MeiGuddet** [comment]
Aaaaah ... hab jetzt unter gemini 7.11.20 in Z 1283 auch endlich die englische Version gefunden: "App vault provides shortcuts for selected third party apps. These shortcuts won't work if you turn the feature off." Und hier die Übersetzung: "App Vault bietet Verknüpfungen für ausgewählte Anwendungen von Drittanbietern. Diese Verknüpfungen werden nicht funktionieren, wenn Sie die Funktion deaktivieren." 
App Vault=Smart/Personal Assistant. Hoffe, die Chinesen entscheiden sich jetzt bald für einen Namen ;-)
