### ISSUE TITLE
Update plurals.xml #124

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI9-ger#125]
@MeiGuddet
https://github.com/berlinux2016/MIUI9-ger/pull/124/commits/ce1920bef24ae7117398747c782531319c037f03

Bitte nicht wieder alles ändern.

jetzt wieder: 5 Risiken,1 Trojaner

%d Risiken, " "1 Trojaner oder halt %d Risiken," 1 Trojaner,"
richtig: 5 Risiken, 1 Trojaner

Akku jetzt:
Eine Std Eine Minute
Ein Tag 5 Std
      Betriebszeit

vorher
1 Std 11 Min
1 Tag 5 Std
 Betriebszeit

Das taucht dann überall so auf!

an vielen Stellen gibt es Probleme damit

z.B. im Kalender, lässt man da bei "one" die 1 weg, steht dann  "Ein1 Tag" da,
es wird dann automatisch die 1 geschrieben

Ich habe mir extra die Mühe gemacht und das vorher auf dem Telefon probiert, es gibt hier auch Screenshots davon.

Groß- und Kleinschreibung ok, ab er bitte mal bei one "%d" oder auch "1" stehen lassen.

Im Satz ok, aber (siehe Akku) Ladezeit, Betriebsdauer, etc. unschön und auch zu lang!

**Comment by MeiGuddet** [comment]
Ok, alles klar, danke für den Hinweis, war mir so nicht klar, wie es nachher in der Darstellung aussieht.
Hatte mich an den anderen Schreibweisen von "one" orientiert.
Wie probierst du das auf dem Handy aus?

**Comment by Henry2o1o** [comment]
Ich bearbeite die APK's gleich auf dem Telefon und schaue mir dann die Ergebnisse an.

**Comment by Henry2o1o** [comment]
hier z.B.
https://user-images.githubusercontent.com/6131799/32168956-cff4e770-bd6e-11e7-9e36-eee888578efb.jpg

**Comment by MeiGuddet** [comment]
Gute Idee. So kann man die Änderung gleich nachvollziehen.
Danke für den Hinweis.

**Comment by Henry2o1o** [comment]
Wie gesagt im Satz ist  "ein/Ein" ok, aber bei Aufzählungen eher nicht.

Das Ersetzen der 1 durch ein/Ein war wohl etwas voreilig.

**Comment by Henry2o1o** [comment]
![32168956-cff4e770-bd6e-11e7-9e36-eee888578efb](https://user-images.githubusercontent.com/6131799/32724767-e4781fbe-c872-11e7-8ea1-e662a5a88b80.jpg)
![photo_2017-11-13_12-55-02 2](https://user-images.githubusercontent.com/6131799/32724768-e4982868-c872-11e7-9a6e-1f7caf4d6e8b.jpg)
![photo_2017-11-13_12-55-02 3](https://user-images.githubusercontent.com/6131799/32724769-e4b1b8d2-c872-11e7-93b7-6d9c100efb16.jpg)

**Comment by Henry2o1o** [comment]
![2](https://user-images.githubusercontent.com/6131799/32724901-4e35c636-c873-11e7-9429-a8c2f0a11b48.jpg)

hier der Kalender
läßt Du "%d" weg, wird da automatisch die 1 gestetzt
