### ISSUE TITLE
lithium_global_images_V9.1.1.0.NAHMIEI_20171106.0000.00_7.0_global

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI9-ger#133]
Ist hier nicht eine bessere dt. Übersetzung integriert?

Habe eben die 
miui.apk /values-de 
settings/values-de
verglichen. 

Übersetzungen sind teilweise ganz anders.

**Comment by berlinux2016** [comment]
schauen besser aus-sollte wir nehmen

**Comment by Henry2o1o** [comment]
Wie regeln wir das? Nicht das diese dann von den anderen Übersetztern wieder umgeändert werden.
Ist ja die orig. Übersetzung , so wie man es zu kaufen bekommt.

**Comment by pareh** [comment]
Ist das Thema noch aktuell?

**Comment by pareh** [comment]
In Global Roms ist doch fast alles in "DU-Form" ich finde unsere Übersetzung besser. Ode geht es hier um ganz bestimmte Abschnitte? @Henry2o1o  @berlinux2016

**Comment by berlinux2016** [comment]
Wir lassen die Übersetzung momentan so. Seitens Xiaomi wird wohl auch unsere demnächst folgen.
