### ISSUE TITLE
Shortcuts im linken Lockscreen falsch übersetzt

### ISSUE THREAD

**Issue by MeiGuddet** [berlinux2016/MIUI9-ger#142]
- **MIUI Version:** 7.11.23
- **Device name:** Gefunden im Redmi Note 4 Nikel

**Screenshot/Description:**Die Shortcuts im linken Lockscreen sind falsch übersetzt: 
Mi Home ist Kontakte
Mi Remote ist Kalender
Mi Bankkarte ist Rechner
Busfahrschein ist Notizen

Den Fehler hat Arquo gestern im eu-Forum gemeldet (Post 69). In welchem String finde ich diese Shortcuts?
![pa_lockscreen](https://user-images.githubusercontent.com/22425869/33229507-800da064-d1d0-11e7-8e09-176a767de8ff.jpg)

**Comment by berlinux2016** [comment]
MIUI9-ger
<https://github.com/berlinux2016/MIUI9-ger/tree/d5a6e8c65bfe367581831a657295be1f6d3eeaaa>
/German
<https://github.com/berlinux2016/MIUI9-ger/tree/d5a6e8c65bfe367581831a657295be1f6d3eeaaa/German>
/main
<https://github.com/berlinux2016/MIUI9-ger/tree/d5a6e8c65bfe367581831a657295be1f6d3eeaaa/German/main>
/MiuiKeyguard.apk
<https://github.com/berlinux2016/MIUI9-ger/tree/d5a6e8c65bfe367581831a657295be1f6d3eeaaa/German/main/MiuiKeyguard.apk>
/res
<https://github.com/berlinux2016/MIUI9-ger/tree/d5a6e8c65bfe367581831a657295be1f6d3eeaaa/German/main/MiuiKeyguard.apk/res>
/values-de
<https://github.com/berlinux2016/MIUI9-ger/tree/d5a6e8c65bfe367581831a657295be1f6d3eeaaa/German/main/MiuiKeyguard.apk/res/values-de>
/strings.xml

ab zeile 121

2017-11-25 11:06 GMT+01:00 Ira <notifications@github.com>:

**Comment by MeiGuddet** [comment]
Die string names passen zwar nicht zur Übersetzung und zum Icon, aber ich habe es jetzt mal geändert (in der englischen Version ist es genauso) :-)
