### ISSUE TITLE
Installierte Apps Absturz

### ISSUE THREAD

**Issue by darki15** [berlinux2016/MIUI9-ger#182]
Die installierten Apps in der Sicherheitsapp können unter Dev Rom 7.12.7 beim Mix 2 nicht geöffnet werden (FC App). Laut xiaomi.eu ein Fehler der Sprache.

Falls ihr weitere Informationen braucht, gebt Bescheid.

**Comment by berlinux2016** [comment]
konnte den Fehler reproduzieren. wird dran gearbeitet. danke

**Comment by berlinux2016** [comment]
Danke für die Fehlermeldung. Fixed in der nächsten Version.
