### ISSUE TITLE
Falscher Text im Lockscreen

### ISSUE THREAD

**Issue by MeiGuddet** [berlinux2016/MIUI9-ger#183]
- **MIUI Version:** MIUI9
- **Device name:** HM4x

**Screenshot/Description:**Jemand im EU-Forum hat einen Fehler auf seinem Lockscreen gemeldet (Post 58): unter dem Clock Widget steht "Kein Netzwerk |" (s. Screenshot). In welcher apk finde ich das?
![screenshot_2017-12-08-08-44-32-587_lockscreen](https://user-images.githubusercontent.com/22425869/33783281-6fdfad4a-dc5c-11e7-9b0c-1be56161ed07.png)

**Comment by Henry2o1o** [comment]
`  <string name="lockscreen_carrier_default">Kein Netzwerk</string>`

MIUI9-ger\German\main\framework-res.apk\res\values-de

**Comment by MeiGuddet** [comment]
Der string ist doch ok. Warum sieht das bei ihm so komisch aus? Bei mir steht da die Sperrbildschirmsignatur. Oder ist das etwa die Einstellung Netzanbieter anzeigen unter Einstellungen > Benachrichtigungen? Dann ist das nämlich kein Fehler.

**Comment by MeiGuddet** [comment]
Hab's bei mir geprüft, es ist die Einstellung Netzanbieter anzeigen unter Einstellungen > Benachrichtigungen. Also kein Fehler.
