### ISSUE TITLE
Zeichensetzung ändern

### ISSUE THREAD

**Issue by Manfred62** [berlinux2016/MIUI9-ger#185]
https://github.com/berlinux2016/MIUI9-ger/blob/6e57ea8ddbc163f272ae9afdfc03c995e8cf16b9/German/main/PersonalAssistant.apk/res/values-de/strings.xml#L32

ändern auf:
<string name="agenda_setting_brief">Termine, Zahlungsaufforderungen und mehr</string>

**Comment by MeiGuddet** [comment]
Danke, wir kümmern drum.

**Comment by berlinux2016** [comment]
fixed
