### ISSUE TITLE
HTML-Sonderzeichen

### ISSUE THREAD

**Issue by MeiGuddet** [berlinux2016/MIUI9-ger#186]
- **MIUI Version:** 9.X.X
- **Device name:** alle

**Screenshot/Description:**
Frage: Müssen bei HTML-Formatierungen in strings, wie z. B. in der Settigs.apk Z 1953 bei < string name="forget_password_button_text" >**< u >**Passwort vergessen**< /u >**< /string > die <>-Zeichen durch die HTML-Zeichen **& lt;** und **& gt**; ersetzt werden? In dieser Apk wurden viele nicht ausgetauscht. Hab das jetzt schon mehrfach in einigen Apk's gesehen und dann auch selbst so geändert, wenn es vorher geändert wurde. Aber ich weiß nicht wirklich, ob es gemacht werden muss. Ich hab gesehen, dass das Zeichen & hier z. B. immer durch **& amp;** ersetzt wird (hab hier Leerzeichen in den String/die HTML-Zeichen eingefügt zur besseren Erkennung). Wär schön, wenn mich heir jemand aufklären könnte ;-).

**Comment by berlinux2016** [comment]
die verwendete sprache hier ist xml. deshalb muss sich zwingend immer an den xml standard gehalten werden. Meist gehen non-konforme XML Beschreibungen gut-können aber zu Compiler Fehlern führen bzw zu FC.  
Hier ist es relativ einfach beschrieben. 
https://www2.informatik.hu-berlin.de/Themen/www/selfhtml/xml/regeln/zeichen.htm
