### ISSUE TITLE
Wetter Widget Übersetzungen

### ISSUE THREAD

**Issue by No3ight** [berlinux2016/MIUI9-ger#187]
- **MIUI Version: MIUI 9.1; 7.11.23 Beta
- **Device name: hermes (Redmi Note 2)

Hallo,

Das Wetter Widget Zeit "Schnellfall" statt "Schneefall".

Die Aktualisierung der Wetterdaten wird in Englisch und nicht in Deutsch angezeigt.

MfG

**Comment by Henry2o1o** [comment]
```
    <string name="weather_type_17">Leichter Schnellfall</string>
    <string name="weather_type_17">Leichter Schneefall</string>
```

**Comment by Henry2o1o** [comment]
**MIUI Version: MIUI 9.1; 7.11.23 Beta
    **Device name: hermes (Redmi Note 2)

Hallo,

Die Aktualisierung der Wetterdaten wird in Englisch und nicht in Deutsch angezeigt.

MfG

**Comment by Henry2o1o** [comment]
Die Aktualisierung der Wetterdaten wird in Englisch und nicht in Deutsch angezeigt.

Screenshot , wenn möglich.

**Comment by MeiGuddet** [comment]
@Henry2o1o: Kann ich den "Schnellfall" irgendwie in meiner vorhandenen runtergeladenen ROM.zip ändern? Wenn ja, wie?
Btw: Bei meinem Ido wird die Aktualisierung der Wetterdaten in deutsch angezeigt (7.12.7).

**Comment by Henry2o1o** [comment]
Hast Du Root?

**Comment by Henry2o1o** [comment]
/system/media/theme/default/gadgets/weather_clock.mtz

entpacken mit winrar

Ordner Content/Strings/strings_de_DE.xml

  <string name="weather_type_17">Leichter Schnellfall</string>

Alles mit winrar öffnen und die xml editieren

**Comment by Henry2o1o** [comment]
Habe es im Github geändert

**Comment by MeiGuddet** [comment]
Nee, hab kein Root. Dann lass ich es halt so bis zum nächsten Update (flashe aber nicht jede Woche).
In der EU-ROM selber kann man nix machen?

**Comment by Henry2o1o** [comment]
In der Zip gehts nicht das diese eine system.new.dat enthählt.
Mit einer Zip zum Flashen würde es gehen.

**Comment by Henry2o1o** [comment]
Nein , da ist ja die system.new.dat drinnen, da kommst Du nicht so einfach ran.

**Comment by MeiGuddet** [comment]
Mist. Ok, dann muss ich eben mit dem Schnellfall leben oder am WE wieder flashen - je nach Art und Umfang der neuen Bugs :-)
