### ISSUE TITLE
repository contains

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI9-ger#188]
https://github.com/berlinux2016/MIUI9-ger

> This repository contains the german translation of the MIUI V9 Weekly ROM Releases from xiaomi.eu, miuipro.ru and other MIUI custom ROMs.

Welche miuipro.ru (The requested URL /roms/ was not found on this server.), miuipro.by?

**Comment by berlinux2016** [comment]
kannst du löschen. die gibt es seit mitte des jahres nicht mehr

2017-12-12 14:13 GMT+01:00 Hen Ry <notifications@github.com>:

**Comment by Henry2o1o** [comment]
Was ist mit der miuipro.by?
Die hat noch paar Extrafeatures und jetzt auch in deutsch.

**Comment by berlinux2016** [comment]
kommt nicht rein- die kupfern nur ab.

**Comment by Henry2o1o** [comment]
Ok, ich habe es korrigiert.
