### ISSUE TITLE
MI GALLERY APP: Missing translation

### ISSUE THREAD

**Issue by Davehimself7586** [berlinux2016/MIUI9-ger#189]
- **MIUI Version:** 7.12.7
- **Device name:** Mi MIX

**Screenshot/Description:**
![screenshot_0_1512920673209](https://user-images.githubusercontent.com/30077820/34008620-3c9852c6-e106-11e7-89c8-86fb2d512a1f.jpg)

MI GALLERY APP:
!!(Click on the searchbar)!!
Missing translation, not only for the German language, It's all in Chinese, not matter which system language is choosen.

**Comment by Henry2o1o** [comment]
MI GALLERY APP ?

**Comment by Davehimself7586** [comment]
Ach, hätte ja auch deutsch schreiben können :D 

Ja, die normale Gallerie/Bilder app von Miui.

**Comment by Henry2o1o** [comment]
Gallerie, sieht bei mir nicht so aus.

**Comment by Davehimself7586** [comment]
auf die Suchleiste geklickt ?

**Comment by Henry2o1o** [comment]
welche suchleiste?

**Comment by Henry2o1o** [comment]
deinen screenshot finde ich nicht

**Comment by Henry2o1o** [comment]
jetzt habe ich die suchleiste in der gallerie

**Comment by Davehimself7586** [comment]
Also das war die letzte Version, 7.12.7, natürlich nichts verändert. Mi Konto ist eingerichtet, auch die automatische Syncronisierung mit der Mi Cloud in den EInstellungen. Sync von Bildern muss natürlich auch aktiviert sein. Wenn man dann die Gallerie öffnet das erste mal kommt auch direkt eine Einblendung ob man die App mit der Bilder-syncronisierung verbinden möchte. Hat man das getan ist die Suchleiste da, über welche man dann direkt seine Mi Cloud durchsuchen kann. 
Und ein Klick auf diese Suchleiste führte zu genau dem Screenshot oben.

**Comment by Davehimself7586** [comment]
oh okay, zu spät :D

**Comment by Henry2o1o** [comment]
kommt bei mir nicht, da sind die ganzen fotos und oben steht wird gesichert...    [Sicherung anhalten]

**Comment by Davehimself7586** [comment]
Das stand bei mir auch auch da, ja. Nach der Syncronisierung erscheint dann aber jedesmal beim Klick auf die Suchleiste das Bild mit den Hieroglyphen.

**Comment by Henry2o1o** [comment]
nach der synchr.?

**Comment by Davehimself7586** [comment]
Yep, als er fertig war mit der Sicherung. Dauert je nach Größe über die Server teils recht lange.

Ich habe übrigens für ein paar Euro dieses Mi Konto hochgestuft zwecks automatischer täglicher Sicherung. Denke zwar nicht, dass es was damit zu tun haben könnte, aber mit fällt sonst nichts ein was irgendwie noch anders sein könnte.

**Comment by Henry2o1o** [comment]
ich habe jetzt auch die zeichen und button, scheint wohl vom server zu kommen

**Comment by Henry2o1o** [comment]
ich bin offline , immer noch da, ich schau mal danach

**Comment by Davehimself7586** [comment]
Hm, okay, danke. ich hatte auch schon gesucht, aber leider nichts gefunden.

**Comment by Henry2o1o** [comment]
bei mir steht oben "分类"

```
<string name="album_name_tags">分类</string>
<string name="album_name_tags">Objekte</string>
```

**Comment by Henry2o1o** [comment]
ich habe die daten von der gallerie gelöscht und offline, zeichen weg

**Comment by Henry2o1o** [comment]
erst kommt auch Foto suchen und kurz danach steht es in chinesisch da, also doch vom server kommend

**Comment by Davehimself7586** [comment]
Okay, dann gibt es jetzt zumindest Klarheit. Danke dir für die Mühe. 
Wie hat das dann die offizielle Global ROM gelöst frag ich mich. 
Wie bei den meisten anderen Sachen wird die komplette Sync-geschichte dann wohl genau wie der "Assistant" oder "swip-up search" einfach komplett gekürzt worden sein schätze ich.

**Comment by Davehimself7586** [comment]
Ich hab es mal direkt an MIUI geschickt über diese Feedback APP. Dann sollten die entsprechende Übersetzungen auf den Servern vornehmen, wenigstens in englisch, denn offiziell gibt es ja auch in der chinesischen Version die englische Sprache und das hab ich schon getestet. Auch mit Systemsprache englisch bleibt es an der Stelle chinesisch.

**Comment by Henry2o1o** [comment]
😀👍
