### ISSUE TITLE
XML-tags displayed wrong, &lt;u>...&lt;/u> in the Apk, in Github correct

### ISSUE THREAD

**Issue by MeiGuddet** [berlinux2016/MIUI9-ger#191]
- **MIUI Version:** 9
- **Device name:** Redmi 3
**Screenshot/Description:** Unter Einstellungen > Synchronisierung wird beim Anmelden in der Mi Cloud  der Link 'Passwort vergessen' fälschlich mit den ausgeschriebenen Zeichen `<u></u>` dargestellt. Wo finde ich die Strings zum Ändern? In der Settings.apk > strings.xml?
![screenshot_2017-12-27-11-21-44-459_com xiaomi account](https://user-images.githubusercontent.com/22425869/34380928-5b8af90a-eb05-11e7-90e8-5eb926bb5af8.png)

**Comment by MeiGuddet** [comment]
In der Settings.apk/strings.xml hab ich sie jedenfalls mal angepasst.

**Comment by MeiGuddet** [comment]
Den Fehler hat noch jemand auf Xiami.eu gemeldet, hier beim Mi Account:
https://xiaomi.eu/community/threads/%C3%9Cbersetzungskorrekturen-miui-v7-deutsch-xiaomi-eu.28411/page-47#post-401377
Dort hab ich die strings auf `&lt;u&gt;Andere Anmeldemöglichkeiten&lt;/u&gt;` angepasst, trotzdem werden sie falsch angezeigt. Kann mir bitte jemand sagen, wo der Fehler liegt? Müssen sie doch so `<u>Andere Anmeldemöglichkeiten</u>` bleiben?

**Comment by ingbrzy** [comment]
remove all html tags from your translation.. they are broken by sorting XML script..

**Comment by MeiGuddet** [comment]
How could this happen? Repair not possible?

**Comment by Henry2o1o** [comment]
Was meint er, im E:\GitHub\Xiaomi.eu-MIUIv9-XML-Compare\ gibt es kein <u>...</u> mehr?

**Comment by Henry2o1o** [comment]
in der Mi Cloud App steht noch 
  `<string name="forget_password"><u>Passwort vergessen</u></string>`

**Comment by Henry2o1o** [comment]
Wo und wo nicht das Angewendet werden soll, vielleicht äußert sich @ingbrzy mal dazu?

**Comment by MeiGuddet** [comment]
@ingbrzy: I changed a lot of those `<u>....</u>` to `&lt;u&gt;....&lt;/u&gt;` just as I was told from @berlinux2016. But nevertheless they are shown wrong like the example from the Mi Account the guy mentioned in this week's eu thread: `&lt;u&gt;Andere Anmeldemöglichkeiten&lt;/u&gt;` is shown `<u>Andere Anmeldemöglichkeiten</u>`. So I'm sorry, I don't know what's wrong. Any tip would be appreciated.

**Comment by MeiGuddet** [comment]
@Henry2o1o: Er sagt, dass im deutschen Github hier noch viele`<u>....</u>` drin sind und das da der Fehler liegt. Aber den oben genannten vom Mi Account hatte ich schon geändert, aber der wird wohl seit der 7.12.21 trotzdem falsch angezeigt (s. Link oben zur eu-ROM). Ich kapier nicht, warum.

**Comment by Henry2o1o** [comment]
What do you mean, in the E: \GitHitHub\Xiaomi. eu-MIUIv9-XML-Compare\ there is no `<u>....</u>` more?
In the "MIUI9-ger" there are many!

das hatte ich ihm geschrieben

**Comment by Henry2o1o** [comment]
![grafik](https://user-images.githubusercontent.com/6131799/34455487-82c4d90a-ed80-11e7-974f-a4633b6877e7.png)

nur in denen gibt es noch ...</u>

**Comment by Henry2o1o** [comment]
ich kann diese alle ändern, aber erst heute Abend,
das geht mit "alle ersetzen" ganz schnell, aber es sind nicht sehr viele

**Comment by MeiGuddet** [comment]
Aber das Problem ist doch , dass die ersetzten falsch angezeigt werden.

**Comment by MeiGuddet** [comment]
Wie hast du die strings oben so schnell gefunden?

**Comment by Henry2o1o** [comment]
CloudService.apk
<string name="forget_password"><u>Passwort vergessen</u></string>

war noch nicht bearbeitet

**Comment by Henry2o1o** [comment]
ich habe eben doch noch alle gändert...

**Comment by MeiGuddet** [comment]
Wo ist der drin: https://xiaomi.eu/community/threads/%C3%9Cbersetzungskorrekturen-miui-v7-deutsch-xiaomi-eu.28411/page-47#post-401377

**Comment by Henry2o1o** [comment]
steht doch darüber, und es ist jetzt auch schon gändert

**Comment by Henry2o1o** [comment]
ich habe alles auf dem Rechner und entsprechende Programme für suchen und ersetzen

da kannst alle apk's durchsuchen und mit einem Ritt bestimmte Wörter,etc. ersetzen/ändern

**Comment by MeiGuddet** [comment]
> steht doch darüber und es ist jetzt auch schon gändert
Was steht wo darüber? Wir reden hier wohl aneinander vorbei. Da geht es doch um die XiaomiAccount.apk, oder nicht? Die hatte ich vor 15 Tagen schon geändert, string wird aber falsch angezeigt. Wieso das?

**Comment by MeiGuddet** [comment]
> ich habe alles auf dem Rechner und entsprechende Programme für suchen und ersetzen
da kann man alle apk's/strings durchsuchen und mit einem Ritt bestimmte Wörter,etc. ersetzen/ändern

Welche Programme? Alles mit Github Desktop und Atom?

**Comment by Henry2o1o** [comment]
Atom nicht, da habe ich keinen Plan, ist auch zu groß dafür. 
Das Find And Replace Tool zum suchen   ersetzen.und halt einen gescheiten Editor.
Und Effective File Search oder Filelocator Pro zum suchen.

**Comment by Henry2o1o** [comment]
Das war bis heute noch unverändert.

CloudService.apk
`<string name="forget_password"><u>Passwort vergessen</u></string>`

**Comment by MeiGuddet** [comment]
Aber was ist mit dem, was ich oben im 2. Kommentar geschrieben habe (und auch 3 Kommentare über deinem letzten)?

**Comment by Henry2o1o** [comment]
Ich dachte es geht um den Screenshot ganz oben und nichts anderes.

**Comment by Henry2o1o** [comment]
Andere Anmeldemöglichkeiten. finde ich nicht, wo steht das

**Comment by Henry2o1o** [comment]
Bei mir steht in der  XiaomiAccount `<u>Andere Anmeldemöglichkeiten</u>` und wird normal und unterstrichen angezeigt.

**Comment by Henry2o1o** [comment]
Ich habe es gefunden, habe alle Apps mit *Cloud* eingefroren. Bei mir wird alles richtig angezeigt.

**Comment by Henry2o1o** [comment]
Bei mir sind beide Strings mit <u> in der  XiaomiAccount.apk, ich habe das Mi Mix.

**Comment by MeiGuddet** [comment]
Ich hab die 7.12.21 und bei mir werden die strings auch so falsch angezeigt wie bei dem Mitglied aus dem Forum, obwohl die strings angepasst sind. Das versteh ich ja eben nicht.

**Comment by Henry2o1o** [comment]
Dann sende mir mal diese Apk, Telegram hast Du ja nicht.
Oder ich lade mir mal schnell die ROM herunter, welche genau (Gerät)?

**Comment by MeiGuddet** [comment]
HM3/ido

**Comment by Henry2o1o** [comment]
Ok

**Comment by Henry2o1o** [comment]
xiaomi.eu_multi_HM3_7.12.21_v9-5.1.zip

**Comment by Henry2o1o** [comment]
habe mal die 28 vom mimix zerlegt

`    <string name="passport_login_using_other_ways">&lt;u>Andere Anmeldemöglichkeiten&lt;/u></string>`

**Comment by MeiGuddet** [comment]
Na super.

**Comment by Henry2o1o** [comment]
Habe die xiaomi.eu_multi_HM3_7.12.21_v9-5.1.zip zerlegt.
Ist in Deiner und in den "Anderen" dann logischer Weiße genauso.

**Comment by cp82** [comment]
Fixes in ad0cf6dbfe0ed5495f74092098eb270a93e81ed6

**Comment by Henry2o1o** [comment]
**Das hätten wir auch machen können, bloß hat sich bisher keiner dazu geäußert!**
