### ISSUE TITLE
Appinfo -> Speicher: Tags sichtbar

### ISSUE THREAD

**Issue by darki15** [berlinux2016/MIUI9-ger#192]
Hallo,

folgendes Problem in der Appinfo -> Speicher:
http://fs1.directupload.net/images/180112/cuclrn3y.png

**Comment by darki15** [comment]
Mix 2 mit 7.12.21

**Comment by Henry2o1o** [comment]
`  <string name="storage_size_large">^1&lt;small&gt;&lt;small&gt; ^2&lt;/small&gt;&lt;/small&gt;</string>`

**Comment by Henry2o1o** [comment]
geändert in
`<string name="storage_size_large">^1<small><small> ^2</small></small></string>`

**Comment by Henry2o1o** [comment]
mal sehen...
