### ISSUE TITLE
Settings.apk\res\values-de\strings.xml:4553: error: Error parsing XML: not well-formed (invalid token)

### ISSUE THREAD

**Issue by usnkreal** [berlinux2016/MIUI9-ger#193]
<string name="settings_notify_phone_recycled">Die registrierte Telefonnummer wurde bereits wiederverwendet. Tippen Sie, um eine weitere Telefonnummer hinzuzufügen.</string

**Comment by MeiGuddet** [comment]
Ist behoben.
