### ISSUE TITLE
Anzeigefehler XML Validation-Seite

### ISSUE THREAD

**Issue by MeiGuddet** [berlinux2016/MIUI9-ger#197]
Die Seite [https://translators.xiaomi.eu/XML_MIUI9-German-de.html](url) wird bei mir mit Quelltext im oberen Bereich angezeigt, s. Screenshot. Wo kann ich das melden?
![anzeigefehler](https://user-images.githubusercontent.com/22425869/36611273-33aca888-18d3-11e8-96fd-9eb55f48865d.jpg)

**Comment by Henry2o1o** [comment]
nach dem 2. F5 drücken ist es weg, kommt aber ab und zu wieder vor

**Comment by MeiGuddet** [comment]
Gibt's ja gar nicht, nach F5 war es jetzt plötzlich weg. Wurde das nur bei mir so angezeigt? War jetzt seit einer Woche so, in allen verfügbaren Browsern (FF, Edge, Palemoon, Vivaldi).

**Comment by Henry2o1o** [comment]
Bei mir ist es nur beim 1 Mal, wenn ich Seite aufrufe, nach F5 ist alles gut :smiley:

**Comment by MeiGuddet** [comment]
Ok, dann schließe ich das hier jetzt, dann isses ja nicht so schlimm.
