### ISSUE TITLE
Lockscreen Redmi Note 4X - Text Bilder Karussell - öffnet Musik player

### ISSUE THREAD

**Issue by nJoy-Android** [berlinux2016/MIUI9-ger#198]
- **MIUI Version:** 9.6 Xiaomi.eu 8.3.8
- **Device name:** Mi Redmi Note 4X Mido

**Screenshot/Description:**

**Comment by MeiGuddet** [comment]
Sorry, kann den Fehler nicht nachvollziehen, anderes Gerät und andere ROM. Vielleicht jemand anders?
@Henry2o1o ?

**Comment by nJoy-Android** [comment]
Montag, 12 März 2018, 07:22nachm. +01:00 von Ira  notifications@github.com :

**Comment by MeiGuddet** [comment]
Fehler gefunden und gefixt.
