### ISSUE TITLE
Einstellungen > Mein Gerät

### ISSUE THREAD

**Issue by Heinzerunzel** [berlinux2016/MIUI9-ger#2]
![screenshot_2017-08-19-16-18-50-559_com android settings](https://user-images.githubusercontent.com/29648253/29489922-a5e8ae00-852c-11e7-93ab-61a14f9ab309.png)

Einstellungen > Mein Gerät 
Akkukapazität, Bildschirmgröße und - auflösung, Kameraauflösung und Android-Verision nicht übersetzt

7.8.17 xiaomi.eu Beta
Mi5S

**Comment by Henry2o1o** [comment]
![settings](https://user-images.githubusercontent.com/6131799/29489991-d0a9fa70-852e-11e7-85e8-3ec4518eb61e.PNG)

**Comment by FireEmerald** [comment]
@Henry2o1o Wenn ihr mit einer Änderung ein Issue schließt/löst könnt ihr einfach in den Betreff/Summary von dem Commit folgendes in einer neuen Zeile hinzufügen:
`Closes #2`
Damit wird dann automatisch Issue #2, geschlossen mit einem Verweis auf euren Commit.

Anstatt einen Screenshot zu posten, nutzt einfach die Funktion auf ein Commit zu verweisen:
`Siehe aaf9743b0d13f94eda97290bee7d312519fa0351.` -> Siehe aaf9743b0d13f94eda97290bee7d312519fa0351.

![2017-08-20 00_14_24-missing strings berlinux2016_miui9-ger aaf9743](https://user-images.githubusercontent.com/1107939/29490438-a2b7ea60-853c-11e7-976c-ad2c0ba0b96c.png)
