### ISSUE TITLE
Redmi Note 4X - Datenverbrauch "dieses Monat" nur Daten wenn Sprache in Englisch

### ISSUE THREAD

**Issue by nJoy-Android** [berlinux2016/MIUI9-ger#200]
- **MIUI Version:** 9.3.6 Xiaomi.eu 8.3.15
- **Device name:** Mido

**Screenshot/Description:**

**Comment by nJoy-Android** [comment]
![screenshot_2018-03-23-07-31-47-798_com miui securitycenter](https://user-images.githubusercontent.com/16748752/37814938-fcc7a732-2e6c-11e8-83ee-f0a44073f349.png)
![screenshot_2018-03-23-07-32-17-688_com miui securitycenter](https://user-images.githubusercontent.com/16748752/37814942-05d8d54e-2e6d-11e8-8ca8-b62877b804ce.png)

**Comment by nJoy-Android** [comment]
Daten nur bei Sprache Englisch - Deutsche keine Daten!

**Comment by berlinux2016** [comment]
Hallo,

leider kann ich es mit meinen Test Redmi Note 4x nicht nachvollziehen. Hier wird es mit der neuesten ROM richtig angezeigt.

**Comment by Henry2o1o** [comment]
ich bin gerade am schauen, irgendwas passt nicht

![photo_2018-03-23_16-50-08](https://user-images.githubusercontent.com/6131799/37839327-727d7b08-2eba-11e8-9cde-a66d74c44b73.jpg)

**Comment by Henry2o1o** [comment]
im engl.

Gestern
Heute
Letzten Monat
Diesen Monat

**Comment by Henry2o1o** [comment]
ergänzt https://github.com/berlinux2016/MIUI9-ger/commit/62901b30f3947b8aa8f904ea3a107b62443b32c9

**Comment by Henry2o1o** [comment]
zu oben kann ich auch nichts finden, schauen wir mal was die Nächste bringt

**Comment by berlinux2016** [comment]
Ich kann den Fehler einfach nicht reproduzieren. Deshalb erst einmal closed und bitte teilen falls mit der neuesten Version ( nicht stabile ) das Problem immer noch auftritt.

**Comment by nJoy-Android** [comment]
Problem würde mit der letzten Beta scheinbar gefixed ;-) Mittwoch, 04 April 2018, 01:00nachm. +02:00 von BerLinuX  notifications@github.com :
