### ISSUE TITLE
Crash at Galerie/Personen

### ISSUE THREAD

**Issue by Hofm4n** [berlinux2016/MIUI9-ger#201]
Hallo Jungs!
Crash in Galerie/Personen, tritt nur bei der Deutschen Sprache auf!

- **MIUI Version:** 8.3.29V2
- **Device name:** Mi 6

**Screenshot/Description:**

**Comment by Hofm4n** [comment]
![2018-03-31 22 53 35](https://user-images.githubusercontent.com/8373340/38170703-3e5cd804-358c-11e8-8838-39f0da84114c.png)
![2018-03-31 22 53 22](https://user-images.githubusercontent.com/8373340/38170704-3e80106c-358c-11e8-9d2d-aee83d787b9c.png)

**Comment by Henry2o1o** [comment]
Bitte Mal ein Screenshot von kurz davor.

**Comment by Hofm4n** [comment]
in der Galerie dann oben Alben dann auf Menschen!
![2018-04-01 09 46 13](https://user-images.githubusercontent.com/8373340/38171040-af5a6102-3591-11e8-8e34-74fade30d4f3.png)

**Comment by ingbrzy** [comment]
Again caused by translated values 
https://github.com/berlinux2016/MIUI9-ger/blob/master/German/main/MiuiGallery.apk/res/values-de/arrays.xml#L42-L50

**Comment by Henry2o1o** [comment]
`    <string-array name="relation_with_me_value">
        <item>myself</item>
        <item>child</item>
        <item>family</item>
        <item>collegue</item>
        <item>classmate</item>
        <item>friend</item>
        <item>unknown</item>
    </string-array>
</resources>
`
and/und

```
  <string-array name="relation_with_me_value">
    <item>Ich</item>
    <item>Kind</item>
    <item>Familie</item>
    <item>Kollege</item>
    <item>Schulkollege</item>
    <item>Freund</item>
    <item>Unbekannt</item>
  </string-array>
```

**Comment by Henry2o1o** [comment]
@Hofm4n
hast Du Root?

**Comment by MeiGuddet** [comment]
@Henry2o1o: Ich werde den Mist, den ich fabriziert habe, wieder rückgängig machen.

**Comment by ingbrzy** [comment]
@Henry2o1o never translate values.. As we discussed in previous commit..

**Comment by Henry2o1o** [comment]
@MeiGuddet 

```
    <string-array name="relation_with_me_value">
        <item>myself</item>
        <item>child</item>
        <item>family</item>
        <item>collegue</item>
        <item>classmate</item>
        <item>friend</item>
        <item>unknown</item>
    </string-array>
```

**Comment by MeiGuddet** [comment]
Yes, I got it. All found string-arrays and strings "value" deleted. Hope it fits now.

**Comment by Hofm4n** [comment]
@Henry2o1o nein leider kein Root und Telegram!

**Comment by Hofm4n** [comment]
@Henry2o1o vielleicht kannst ja die APK auf meine Email schicken!? hofer.manuel1@gmx.at

**Comment by berlinux2016** [comment]
Wird mit der nächsten Version behoben. Danke für die Bug Meldung.
