### ISSUE TITLE
Mi Konto Login

### ISSUE THREAD

**Issue by berufsking** [berlinux2016/MIUI9-ger#54]
- **MIUI Version:** 9 (7.9.7 beta)
- **Device name:** Redmi 4X (santoni)

**Screenshot/Description:**
Fehlerhafte tag Struktur in der xml Datei beim Login für das Mi Konto.

Screen: 
http://www.abload.de/image.php?img=x2lxg.jpg

**Comment by berufsking** [comment]
Dasselbe Problem taucht auch im "Abmelden" Dialog auf.

Screen:
https://puu.sh/xvnME/e36acc741e.png

**Comment by FireEmerald** [comment]
ref #56 ?

**Comment by berlinux2016** [comment]
Fixed & closed + Danke
