### ISSUE TITLE
Einstellungen "Search Settings"

### ISSUE THREAD

**Issue by berufsking** [berlinux2016/MIUI9-ger#55]
- **MIUI Version:** 9 (7.9.7 beta)
- **Device name:** Redmi 4X (santoni)

**Screenshot/Description:**
Screen: http://www.abload.de/image.php?img=amkq6.jpg

**Comment by WorXeN** [comment]
Siehe https://github.com/berlinux2016/MIUI9-ger/pull/58/files#diff-b6ad3fee97fd5ce063e9ff8f57fbb444
