### ISSUE TITLE
USB-Optionen

### ISSUE THREAD

**Issue by Heinzerunzel** [berlinux2016/MIUI9-ger#6]
7.8.24 beta
Mi5S

![img_20170826_195235](https://user-images.githubusercontent.com/29648253/29745326-0c9c9acc-8ab8-11e7-9721-f4a84785d6ae.png)
![img_20170826_195319](https://user-images.githubusercontent.com/29648253/29745327-12617d4c-8ab8-11e7-8b5d-ba2ac368f4f0.png)

bei USB-Verbindung teils unübersetzte Funktionen

**Comment by pareh** [comment]
Die Zeilen sind eigentlich übersetzt. Stelle bitte  das Telefon auf deutsch um und starte es neu. Anschließend teste bitte noch einmal, ob diese Info immer noch auf englisch ist.

**Comment by Heinzerunzel** [comment]
Das Problem besteht leider weiterhin.

**Comment by FireEmerald** [comment]
Beim MiNote Pro 7.8.24 beta ist es ebenfalls noch auf English - falls es bereits übersetzt wurde einfach mal die nächste Version abwarten und dann erneut schauen ob es immer noch auf English ist.

**Comment by Heinzerunzel** [comment]
Leider immer in 7.8.31 beta
Mi5S

**Comment by pareh** [comment]
fixed dd4fce4c05c2ba296d2fb6a725195b9bdd289c43
