### ISSUE TITLE
recompile issue

### ISSUE THREAD

**Issue by ingbrzy** [berlinux2016/MIUI9-ger#62]
`Settings.apk/res/values-de/arrays.xml:80: error: Found text "  " where item tag is expected
W: 
W: Settings.apk/res/values-de/strings.xml:9: error: Found text "  " where item tag is expected
W: 
`

`SecurityCenter.apk/res/values-de/plurals.xml:336: error: Found text "  " where item tag is expected
`

`Updater.apk/res/values-de/strings.xml:292: error: Found text "  " where item tag is expected
`

`MiuiCamera.apk/res/values-de/strings.xml:5: error: Found text "  " where item tag is expected
W: 
`

You should change your xml editor.. current one is breaking xmls!!!

**Comment by ingbrzy** [comment]
@WorXeN you should use notepad++ as your current tool is breaking XMLs...

**Comment by ingbrzy** [comment]
![screenshot from 2017-09-12 05-46-47](https://user-images.githubusercontent.com/1762519/30307344-e060c9ec-977d-11e7-8c67-c3c9c487860c.png)

Do not put double space after each string!

**Comment by WorXeN** [comment]
Ok...thats strange, because i´m using the web based github Editor...

**Comment by ingbrzy** [comment]
`Updater.apk/res/values-de/strings.xml:289: error: Found text "
W:   " where item tag is expected
W: 
`

`MiuiSystemUI.apk/res/values-de/strings.xml:59: error: Found text "
W:   " where item tag is expected
W: `
