### ISSUE TITLE
Entwickleroptionen

### ISSUE THREAD

**Issue by Sedumjo** [berlinux2016/MIUI9-ger#7]
7.8.24 beta
MI 5s

Pfad: Einstellungen -> Weitere Einstellungen -> Entwickleroptionen

![entwickleroptionen](https://user-images.githubusercontent.com/29120378/29816382-303e2fce-8cb4-11e7-98be-ba5218d3384b.png)

**Comment by pareh** [comment]
Wurde hier übersetzt 7e4edc5dab30aa61318fa769d84797865a3303fa
Bitte melden, falls beim nächsten Update immer noch Englisch.

**Comment by Sedumjo** [comment]
Meldung ^^

Auch in Version 7.9.8 wird es noch nicht übersetzt angezeigt.
Ich habe im Verweis gesehen, dass die beiden Stellen eigentlich übersetzt sein müssten, zumindest mit meinem sehr laienhaften Wissen.
Ich weiß, dass ihr hier tolle Arbeit leistet, wofür ich euch noch mal "Danke" sagen möchte. 
Ich habe keine Ahnung, woran es liegt.

**Comment by lynx7** [comment]
bin hier mehr der orthografieprofi als der it kenner, kann aber sagen, dass es nicht immer sehr einfach die richtige Stelle zu finden. Nur so meine Erfahrung.

**Comment by berlinux2016** [comment]
danke + fixed in nächsten Freitag Version + closed
