### ISSUE TITLE
Einstellungen, neue Appübersicht

### ISSUE THREAD

**Issue by Heinzerunzel** [berlinux2016/MIUI9-ger#81]
Mi5S
xiaomi.eu beta 7.10.12

![img_20171013_100949](https://user-images.githubusercontent.com/29648253/31536386-b2342944-affe-11e7-933e-8a445030d3c0.png)

Einstellungen > Alle Apps >...
Nicht übersetzte Menüpunkte

**Comment by Henry2o1o** [comment]
Stimmt

**Comment by Henry2o1o** [comment]
Ist wohl noch nicht übernommen wurden, die Strings sind übersetzt.

**Comment by WorXeN** [comment]
da es eine neue "Funktion" ist werden die Strings dafür noch nicht in unserem Git sein...
bin aktuell noch dabei die German Strings auf Version 7.10.9 zu updaten.
Das Kopieren aus der Originalquelle dauert halt immer ein wenig :)
