### ISSUE TITLE
Emergencyinfo.apk

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI9-ger#82]
Auf welchem Gerät ist diese Funktion vorhanden?

Ich kann diese nur mit, z.B. mit dem Nova Launcher, sichtbar machen.

**Comment by Henry2o1o** [comment]
Ist wohl noch nicht übernommen wurden, die Strings sind übersetzt.

**Comment by FireEmerald** [comment]
Assignments sind zum Aufteilen von Issues gedacht. Wenn du einzelne Leute explizit Fragen möchtest, verwende @Henry2o1o .

**Comment by berlinux2016** [comment]
das weiss ich ;-) henry assigns ja zu mir ;-)

2017-10-13 11:51 GMT+02:00 FireEmerald <notifications@github.com>:

**Comment by lynx7** [comment]
soweit ich weiss ist diese funktion auf einigen versionen deaktiviert. als cpmiui benützer weiss ich, dass dieses emergency zeugs auf cpmiui deaktiviert ist. weiss nicht ob das bei der .eu version auch so ist.
