### ISSUE TITLE
FileExplorer.apk

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI9-ger#86]
MIUI9

so lassen, oder anpassen?

**jetzt:**
   <string name="share_title_01">%1$s Hier ist ein cooles Video! %2$s</string>
  <string name="share_title_02">%1$s Hier ist ein cooles Video!</string>
  <string name="share_title_03">%1$s Hier ist ein cooles Video! %2$s</string>
  <string name="share_title_04">%1$s Ich habe ein Video geteilt, schau es mal an! %2$s</string>
  <string name="share_title_05">%1$s Ich habe ein Video geteilt, schau es mal an! %2$s</string>
  <string name="share_title_06">%1$s Ich habe ein Video geteilt, schau es mal an! %2$s</string>
  <string name="share_title_07">%s Ich habe ein Video geteilt, schau es mal an!</string>
  <string name="share_title_08">%s Ich habe ein Video geteilt, schau es mal an!</string>
  <string name="share_title_09">%s Ich habe ein Video geteilt, schau es mal an!</string>

**orig:**
  
    <string name="share_title_01">%1$s全网热播的小视频，删前速看%2$s</string>
    <string name="share_title_02">%s这个视频小很有料，看完我惊呆了</string>
    <string name="share_title_03">%1$s快来，这个视频再不看就没有了%2$s</string>
    <string name="share_title_04">%1$s震惊网友的小视频，分享给你…%2$s</string>
    <string name="share_title_05">这个小视频好赞%1$s%2$s，一起来看</string>
    <string name="share_title_06">身边人都在看的%1$s火爆视频%2$s，就差你了</string>
    <string name="share_title_07">%s上传视频送大奖，快来「有料」</string>
    <string name="share_title_08">这个小视频我给满分%s，你也来看</string>
    <string name="share_title_09">%s我正在看这个小视频，分享给你</string>

**mit google:** :-)

%1$s ganzes netzwerk hit small video, delete front speed siehe  %2$s
%s dieses video ist sehr materiell, nach dem beobachten war ich von der  betäubt
%1$s bald wird dieses video nicht die %2$s
%1$s schockiert netizens kleines video, aktien an sie ... %2$s
dieses kleine video ist gut %1$s%2$s, let's see </string>
um die menschen blicken auf die %1$s hot video %2$s, sie sind schlechte
%s upload video um den jackpot zu verschicken, come" have material "
dieses kleine video ich gebe volle punktzahl %s, siehst du auch
%s ich beobachte dieses kleine video und teile es mit dir

**Comment by berlinux2016** [comment]
Lassen wir erst einmal so
