### ISSUE TITLE
Sicherheitsapp > Werkzeuge; Uhr > Wecker

### ISSUE THREAD

**Issue by MeiGuddet** [berlinux2016/MIUI9-ger#90]
- **MIUI Version:** 7.10.12
- **Device name:** Redmi 3/IDO

**Screenshot/Description:** 
1. In der Sicherheitsapp unter Werkzeuge heißt der letzte Button "Roter Umschlaga..." (mehr wird nicht angezeigt; weiß nicht, was es bedeutet). Wenn man diesen Button drückt, kommt man auf eine schöne rote Seite ;-) in komplett chinesischer Schrift. Was ist das für eine App?
2. Bin gerade von der 7.5.18 auf die 7.10.12 gewechselt und musste einiges neu einstellen. Dabei habe ich die Funktion gesucht, die den Wecker auch im ausgeschalteten Zustand auslöst. Nach Umstellen auf englisch habe ich sie dann gefunden in den Einstellungen der Uhr: "Shutdown Alarm - Alarm will ring after powerde off" - die deutsche Übersetzung ist IMHO missverständlich: "Standby Alarm - Standby Alarm ist AUS/AN". Könnt  ihr das evtl. etwas wörtlicher übersetzen?

**Comment by Henry2o1o** [comment]
```
    <string name="card_main_hbassistant_title">Red envelope assistant</string>
    <string name="card_main_hbassistant_summary">Use this tool to grab the envelopes faster</string>

    <string name="card_main_hbassistant_title">红包助手</string>
    <string name="card_main_hbassistant_summary">小米官方红包提醒工具</string>

Roter Umschlagassistent
Millet offiziellen roten Umschlag Erinnerung Werkzeug
```

**Comment by MeiGuddet** [comment]
Ja, sieht ganz so aus, als sei er das, passt vom Namen her:
![screenshot_2017-10-18-16-44-59-780_com miui securitycenter](https://user-images.githubusercontent.com/22425869/31725202-0d61d392-b424-11e7-82b4-6d2b32c0df6a.png)
![screenshot_2017-10-18-16-45-04-092_com miui securitycenter](https://user-images.githubusercontent.com/22425869/31725203-0d87f950-b424-11e7-95aa-cc1c2bae7fc0.png)
Wozu braucht man den?

**Comment by Henry2o1o** [comment]
keine Ahnung

![photo_2017-10-18_19-16-10](https://user-images.githubusercontent.com/6131799/31735150-4c8c499a-b441-11e7-807c-5a868b559075.jpg)

**Comment by berlinux2016** [comment]
Der Fehler liegt nicht an der Übersetzung sondern die App gehört raus in der ROM von Redmi 3 IDO. Gebs weiter.....deshalb in unserem Github closed.
