### ISSUE TITLE
Einstellungen

### ISSUE THREAD

**Issue by Henry2o1o** [berlinux2016/MIUI9-ger#91]
unter "Mein Gerät" ist oben wieder alles in Englisch

**Comment by Henry2o1o** [comment]
![photo_2017-10-22_10-32-43](https://user-images.githubusercontent.com/6131799/31860032-b2570212-b714-11e7-95fa-6a52895101dc.jpg)

Strings sind in der values.de/strings.xml vorhanden?

**Comment by berlinux2016** [comment]
Ist kein Problem von uns. Ist ein Fehler in der neuen MIUI Version

**Comment by Henry2o1o** [comment]
Was ist der Unterschied zwischen strings-de und strings-de-rDE?
