### ISSUE TITLE
Translation issue - data usage - English german

### ISSUE THREAD

**Issue by nJoy-Android** [berlinux2016/MIUI9-ger#99]
- **MIUI Version:** 9.1
- **Device name:** Redmi note 4X

**Screenshot/Description:**
Pulldown menu shows "today and remaining" instead of "Heute und verbleibend"

**Comment by Heinzerunzel** [comment]
Mi5S
xiaomi.eu beta 7.11.2

gleiches Problem:
![img_20171104_182532](https://user-images.githubusercontent.com/29648253/32407812-7244b190-c18e-11e7-8c12-2a998e556fa7.png)

**Comment by Henry2o1o** [comment]
Es sind sehr viel neue Strings dazu gekommen.

**Comment by WorXeN** [comment]
Behoben in der Nächsten Version
149f51b24a8f348b67b28d46c959e36aa24948d4
